### **Incode Vision Project Based Internship**

### **Data Science**

###**Track Code : DS**

Task - 1 : Data Cleaning and preprocessing

In [ ]:
# import libraries
import pandas as pd
import numpy as np

In [ ]:
# Load Dataset
df = pd.read_csv('/dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
# Initial data inspection
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
print('row :' ,df.shape[0])
print('column :' ,df.shape[1])

row : 10000
column : 8

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
# remove unnecessary column
df=df.drop(columns=['Transaction ID'])

In [ ]:
# correct data types
num_cols = ['Quantity','Price Per Unit','Total Spent']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
# convert transaction date
df['Transaction Date']= pd.to_datetime(df['Transaction Date'],errors = 'coerce')

In [ ]:
# Handle missing values in item
df=df.dropna(subset=['Item'])

In [ ]:
print(df['Item'].isnull().sum())
print(df.shape)

0
(9667, 7)

In [ ]:
#Handle Missing numerical values
df['Quantity']=df['Quantity'].fillna(df['Quantity'].median())
df['Price Per Unit']=df['Price Per Unit'].fillna(df['Price Per Unit'].median())
df['Total Spent']=df['Total Spent'].fillna(df['Quantity']*df['Price Per Unit'])

In [ ]:
#handle missing categorical values
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN','Unknown',''],pd.NA)
df['Location'] = df['Location'].replace(['UNKNOWN','Unknown',''],pd.NA)
df['Payment Method'] = df['Payment Method'].fillna('Unknown')
df['Location'] = df['Location'].fillna('Unknown')

In [ ]:
# Validate the clean Dataset
print(df.shape)
print(df.isnull().sum())
print(df.dtypes)
print(df.duplicated().sum())
print(df.head())

(9667, 7)
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    442
dtype: int64
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object
255
     Item  Quantity  Price Per Unit  Total Spent  Payment Method  Location  \
0  Coffee       2.0             2.0          4.0     Credit Card  Takeaway
1    Cake       4.0             3.0         12.0            Cash  In-store
2  Cookie       4.0             1.0          4.0     Credit Card  In-store
3   Salad       2.0             5.0         10.0         Unknown   Unknown
4  Coffee       2.0             2.0          4.0  Digital Wallet  In-store

  Transaction Date
0       2023-09-08
1       2023-05-16
2       2023-07-19
3       2023-04-27
4       2023-06-11